### ISSUE TITLE
kubeconfig download scripts are missing hosts (via button and text)

### ISSUE THREAD

**Issue by hh** [sharingio/pair#101]

**Comment by hh** [comment]
kmtemp needs more XXX
otherwise it fails

**Comment by hh** [comment]
Also, use `kubectl cluster-info` as the test command.

**Comment by BobyMCbobs** [comment]
Currently it's XXXXX. XXX is the minimum for Linux; what works on macOS?

**Comment by hh** [comment]
https://pair.sharing.io/instances/id/hh

I did a quick check and realised the issue is that the text for the copy icon and the string box do not match:

The text box looks fine:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/31331/119104399-53cd5080-ba70-11eb-8f2f-6212a2058002.png">

But the copy icon gives the following (no XXXX or hostname):
```
export KUBECONFIG=$(mktemp -t kubeconfig) ; curl -s https:///public-instances/5c193ca2-a35d-4957-87ba-FOOBARBAZf9f/hh/kubeconfig > "$KUBECONFIG" ; kubectl api-resources
```

**Comment by BobyMCbobs** [comment]
Fixed in https://github.com/sharingio/pair/commit/c8f944c1b7b1145ec1127f4c85dc20a73ddded5a
