### ISSUE TITLE
Clicking on clipboard icon next to attach to cluster command doesn't work

### ISSUE THREAD

**Issue by hh** [sharingio/pair#106]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/31331/119880911-d8443580-bf80-11eb-99db-ecedfcee8bc4.png">

Clicking here does not result in the clipboard being populated.

**Comment by BobyMCbobs** [comment]
This should've been fixed in ca657273643d3059fff7163d44ff9269769b105c

Please reopen if it wasn't corrected
