### ISSUE TITLE
Request less permissions via GitHub OAUTH app

### ISSUE THREAD

**Issue by hh** [sharingio/pair#13]
Research what OAUTH permissions we require and are requesting:

I think we mainly want the ability to push/pull to repos.

For deploying prow, we may want something deeper like:
- creating/managing hooks
- comments on tickets (as a bot)

== current requested access ==

**Personal user data**
_Full access_

This application will be able to **read and write all user data.** This includes the following:

- Private email addresses
- Private profile information
- Followers

**Comment by zachmandeville** [comment]
implemented in https://github.com/sharingio/pair/commit/29a323d0b012e93a9689bf298a06779383152b30
