### ISSUE TITLE
Pass GitHub-Token from OAUTH to cluster-api for use with pair/prow

### ISSUE THREAD

**Issue by hh** [sharingio/pair#15]
https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps

This should be able to be passed to humacs container as a var or secret file that is used by emacs to git push/pull at a minimum.

**Comment by BobyMCbobs** [comment]
Added on _cluster-api-manager_ side in 7c88eb2

**Comment by zachmandeville** [comment]
implemented in https://github.com/sharingio/pair/pull/44
