### ISSUE TITLE
Roll back to the main branch

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/pair#176]
Recently some of us where having issues with logging into Pair.
Since
https://github.com/sharingio/pair/issues/174
is resolved via resetting auth access for the Pair OAuth app, given new permissions not being requested,
There's a chance that the main branch might work again for all of us.

Rerun a CI job on the main branch for deploy and use Pair not on the _the-backpoint-and-please-work-edition_ branch

**Comment by zachmandeville** [comment]
i like it, but am wondering if this issue might be better in `sharingio/pair`?

**Comment by BobyMCbobs** [comment]
Sounds good @zachmandeville, I'll move it over

**Comment by BobyMCbobs** [comment]
Rolled back in https://github.com/sharingio/pair/releases/tag/2022.09.02.1411

**Comment by BobyMCbobs** [comment]
This was completed.
