### ISSUE TITLE
Real IP header pass through

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/pair#25]
# Goal

Use the HTTP header _X-Real-Ip_ to keep track of IPs

**Comment by zachmandeville** [comment]
This is to enable better logging so we can see who exactly created which box.

**Comment by hh** [comment]
NGINX sets HTTP Header `X-Real-Ip: ` because the SRC IP on the http request, comes from nginx.

The backend would like to see this too, so also set your http header to the same value.

**Comment by hh** [comment]
Might not by X-Real-IP:, would be nice to have the frontend have a variable set to change which header it receives and sends.
