### ISSUE TITLE
Ensure instance.spec.setup.timezone is passed to cluster-api-manager

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/pair#28]
# Issue

Without a timezone set operations will fail.
A timezone should be set in the POST object:

```json
{
  "spec": {
    "setup": {
      "timezone": "Pacific/Auckland"
     }
   }
}
```

**Comment by hh** [comment]
@BobyMCbobs I think you set a default recently.

@zachmandeville Can you pull the users timezone from Github or from the browser?

**Comment by zachmandeville** [comment]
implemented in https://github.com/sharingio/pair/pull/65
