### ISSUE TITLE
SOS ssh url available 

### ISSUE THREAD

**Issue by hh** [sharingio/pair#31]
If you have the packet machine UUID and DC, you can constructe the SOS console URL.
It's readonly I think, but allows for a bit more information.
Let's add it to the instance page.

```
$ ssh c457f7a2-8898-411d-96af-bd2596601afb@sos.sjc1.platformequinix.com
[Read-only SOS Session. Use ~? for help.]
```

**Comment by zachmandeville** [comment]
implemented in https://github.com/sharingio/pair/pull/65
