### ISSUE TITLE
Optional full instance name for BaseDNSName

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/pair#45]
Due to certificates, it might be good to provide an optional unique DNS name for each instance

**Comment by hh** [comment]
We talked about this possibility:

For the first instance (if one doesn't currently exist)
- USERNAME is the name of the cluster
- USERNAME.ii.sharing.io is the BaseDNSName

For the second and further
- USERNAME-ABCD is the name of the cluster (what we currently do)
- USERNAME-ABCD.ii.sharing.io is the BaseDNSName

**Comment by BobyMCbobs** [comment]
Completed in a7082c9f326b88a5652523dbf0a394c07b0a0c35
