### ISSUE TITLE
Allow specifying the BaseDNSName IF admin

### ISSUE THREAD

**Issue by hh** [sharingio/pair#47]
As an admin, rather than forcing the default of:
- GITHUBUSER as the cluster name
- GITHUBUSER.ii.sharing.io as the BaseDNSName

An Admin should be able to provide:
- SPECIFIED as the cluster name
- SPECIFIED.SOMETHING.UNDER.sharing.io

**Comment by zachmandeville** [comment]
implemented in https://github.com/sharingio/pair/pull/65
