### ISSUE TITLE
Populate GITHUB_TOKEN in humacs pod as ENV

### ISSUE THREAD

**Issue by hh** [sharingio/pair#48]
https://cli.github.com/manual/

ii@hh-humacs-0:~$ gh help environment

GH_TOKEN, GITHUB_TOKEN (in order of precedence): an authentication token for github.com
API requests. Setting this avoids being prompted to authenticate and takes precedence over
previously stored credentials.

**Comment by BobyMCbobs** [comment]
This is available now
